/* Copyright (C) 2012-2016 Tal Aloni <tal.aloni.il@gmail.com>. All rights reserved.
 * 
 * You can redistribute this program and/or modify it under the terms of
 * the GNU Lesser Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 */
using System;
using System.Collections.Generic;
using System.Text;
using System.Net;
using Utilities;

namespace ISCSI.Server
{
    public class TransferEntry
    {
        public SCSICommandPDU Command;
        public uint NextR2TSN;

        public TransferEntry(SCSICommandPDU command, uint nextR2TSN)
        {
            Command = command;
            NextR2TSN = nextR2TSN;
        }
    }

    public class ConnectionParameters
    {
        public static int DeclaredMaxRecvDataSegmentLength = 262144;

        public ushort CID; // connection ID, generated by the initiator
        public string InitiatorName = String.Empty;
        public IPEndPoint InitiatorEndPoint;

        /// <summary>
        /// per direction parameter that the target or initator declares.
        /// maximum data segment length that the target (or initator) can receive in a single iSCSI PDU.
        /// </summary>
        public int InitiatorMaxRecvDataSegmentLength = DefaultParameters.Connection.MaxRecvDataSegmentLength;
        public int TargetMaxRecvDataSegmentLength = DeclaredMaxRecvDataSegmentLength;

        public uint StatSN = 0; // Initial StatSN, any number will do
        // Dictionary of current transfers: <transfer-tag, TransferEntry>
        private Dictionary<uint, TransferEntry> n_transfers = new Dictionary<uint, TransferEntry>();

        public TransferEntry AddTransfer(uint transferTag, SCSICommandPDU command, uint nextR2TSN)
        {
            TransferEntry entry = new TransferEntry(command, nextR2TSN);
            n_transfers.Add(transferTag, entry);
            return entry;
        }

        public TransferEntry GetTransferEntry(uint transferTag)
        {
            TransferEntry result;
            n_transfers.TryGetValue(transferTag, out result);
            return result;
        }

        public void RemoveTransfer(uint transferTag)
        {
            n_transfers.Remove(transferTag);
        }
    }
}
